$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: extraction
version: 1
display_name: Extraction
type: command
code: ../action_extraction
command: >-
  python extraction.py 
  --input ${{inputs.input}} 
  --output ${{outputs.output}}
inputs:
  input:
    type: uri_folder
outputs:
  output:
    type: uri_folder
