$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: integration
version: 1
display_name: Integration
type: command
code: ../action_extraction
command: >-
  python integration.py 
  --input ${{inputs.input}} 
  --output ${{outputs.output}}
inputs:
  input:
    type: uri_folder
outputs:
  output:
    type: uri_folder
